In [1]:
from sklearn.model_selection import KFold
fold=KFold(n_splits=4)
fold

KFold(n_splits=4, random_state=None, shuffle=False)

In [2]:
import numpy as np
data=np.arange(1,16)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
for train_index,test_index in fold.split(data):
    print(train_index,test_index)

[ 4  5  6  7  8  9 10 11 12 13 14] [0 1 2 3]
[ 0  1  2  3  8  9 10 11 12 13 14] [4 5 6 7]
[ 0  1  2  3  4  5  6  7 12 13 14] [ 8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11] [12 13 14]
