In [31]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_csv("C:/Users/User/Downloads/carprices.csv")
data

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [33]:
dummies=pd.get_dummies(data["Car Model"])
dummies

Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [34]:
merge=pd.concat([data,dummies],axis=1)
merge

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6    False    True   
1                  BMW X5    35000          34000         3    False    True   
2                  BMW X5    57000          26100         5    False    True   
3                  BMW X5    22500          40000         2    False    True   
4                  BMW X5    46000          31500         4    False    True   
5                 Audi A5    59000          29400         5     True   False   
6                 Audi A5    52000          32000         5     True   False   
7                 Audi A5    72000          19300         6     True   False   
8                 Audi A5    91000          12000         8     True   False   
9   Mercedez Benz C class    67000          22000         6    False   False   
10  Mercedez Benz C class    83000          20000         7    False   False   
11  Mercedez Benz C class    79000          21000         7    False   False   
12  Mercedez Benz C class    59000          33000         5    False   False   

    Mercedez Benz C class  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
5                   False  
6                   False  
7                   False  
8                   False  
9                    True  
10                   True  
11                   True  
12                   True

In [35]:
merge=merge.drop(["Car Model"],axis=1)
merge

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000          18000         6    False    True                  False
1     35000          34000         3    False    True                  False
2     57000          26100         5    False    True                  False
3     22500          40000         2    False    True                  False
4     46000          31500         4    False    True                  False
5     59000          29400         5     True   False                  False
6     52000          32000         5     True   False                  False
7     72000          19300         6     True   False                  False
8     91000          12000         8     True   False                  False
9     67000          22000         6    False   False                   True
10    83000          20000         7    False   False                   True
11    79000          21000         7    False   False                   True
12    59000          33000         5    False   False                   True

In [36]:
y=merge["Sell Price($)"]
x=merge.drop(["Sell Price($)"],axis=1)

In [37]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [47]:
model.predict([[45000,4,0,0,1]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721061])

In [48]:
model.predict([[86000,7,0,1,0]])

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11080.74313219])

In [44]:
y_pred=model.predict(x)
y_pred

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [45]:
print(x.shape)
print(y.shape)
print(y_pred.shape)

(13, 5)
(13,)
(13,)


In [39]:
from sklearn.metrics import r2_score

In [46]:
r2=r2_score(y,y_pred)
r2

0.9417050937281083