In [3]:
!where python


C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe
C:\Users\User\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe


In [4]:
!pip install tensorflow --user

  Using cached tensorflow-2.18.0-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
Using cached tensorflow-2.18.0-cp312-cp312-win_amd64.whl (7.5 kB)



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import tensorflow as tf
print("TensorFlow version:",tf.__version__)

In [34]:
print(tf.constant([[1,2],[3,4]]))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [35]:
print(tf.zeros([2,2]))

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [36]:
print(tf.ones([2,3]))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [16]:
# Basic Arithmetic Operators

In [17]:
a=tf.constant(2)
b=tf.constant(3)
print("Tensor a:",a)
print("Tensor b:",b)

Tensor a: tf.Tensor(2, shape=(), dtype=int32)
Tensor b: tf.Tensor(3, shape=(), dtype=int32)


In [19]:
print(tf.add(a,b))

tf.Tensor(5, shape=(), dtype=int32)


In [20]:
print(tf.multiply(a,b))

tf.Tensor(6, shape=(), dtype=int32)


In [21]:
print(tf.divide(b,a))

tf.Tensor(1.5, shape=(), dtype=float64)


In [ ]:
# Matrix Multiplication

In [23]:
matrix1=tf.constant([[1,2],[3,4]])
matrix2=tf.constant([[5,6],[7,8]])

In [24]:
print(tf.matmul(matrix1,matrix2))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
# Variable Operations

In [26]:
x=tf.Variable(5.0)

In [27]:
print(x.assign_add(1.0))

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=6.0>


In [ ]:
# Automatic Differentiation

In [44]:
x=tf.Variable(3.0)

In [45]:
with tf.GradientTape() as tape:
    y=x**2

In [46]:
print(tape.gradient(y, x))

tf.Tensor(6.0, shape=(), dtype=float32)


In [ ]:
# Broadcasting

In [47]:
a=tf.constant([1,2,3])
b=tf.constant(5)

In [48]:
print(tf.add(a,b))

tf.Tensor([6 7 8], shape=(3,), dtype=int32)


In [ ]:
# Reducing Operations

In [31]:
print(tf.reduce_sum([[1,2,3],[4,5,6]]))

tf.Tensor(21, shape=(), dtype=int32)


In [33]:
print(tf.reduce_sum([[1, 2, 3], [4, 5, 6]], axis=0))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
# Reshaping and Transposing Tensors

In [10]:
tensor=tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
print(tf.reshape(tensor,[4, 2]))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


In [11]:
print(tf.transpose(tensor))

tf.Tensor(
[[1 5]
 [2 6]
 [3 7]
 [4 8]], shape=(4, 2), dtype=int32)


In [ ]:
# Element-wise Operations

In [12]:
tens=tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
print(tf.pow(tens,2))

tf.Tensor(
[[ 1  4  9 16]
 [25 36 49 64]], shape=(2, 4), dtype=int32)


In [ ]:
# Numpy compatibility

In [1]:
import numpy as np
import tensorflow as tf

In [3]:
num=np.array([[1,2],[3,4]])

In [4]:
print(tf.convert_to_tensor(num))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [5]:
print(num)

[[1 2]
 [3 4]]


In [ ]:
# Keras

In [51]:
import numpy as np
from tensorflow.keras import layers,models

In [52]:
def generate_addition_data(samples=10000):
    x1=np.random.randint(0,100,size=(samples,))
    x2=np.random.randint(0,100,size=(samples,))
    y=x1+x2
    return np.column_stack((x1,x2)),y

In [53]:
x_train,y_train=generate_addition_data(10000)
x_test,y_test=generate_addition_data(10000)

In [54]:
model=models.Sequential()
model.add(layers.Dense(64,activation='relu',input_shape=(2,)))
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(1))
model.compile(optimizer='adam',loss='mean_squared_error')

In [62]:
model.fit(x_train,y_train,epochs=50,batch_size=32,validation_split=0.2)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 2479.0496 - val_loss: 0.4641
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3009 - val_loss: 0.0988
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0736 - val_loss: 0.0276
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0212 - val_loss: 0.0137
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0135 - val_loss: 0.0101
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0094 - val_loss: 0.0065
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0066 - val_loss: 0.0044
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0026 - val_loss: 0.0019
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0019 - val_loss: 0.0018
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0015 - val_loss: 0.0011
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/s

In [63]:
test_loss=model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0205


In [64]:
test_data=np.array([[10,20],[50,60],[23,45]])
predictions=model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step


In [65]:
print('Test data:',test_data)
print('Predicted sums:',predictions)

Test data: [[10 20]
 [50 60]
 [23 45]]
Predicted sums: [[ 30.03368 ]
 [110.087265]
 [ 68.062744]]
